language: node_js

node_js:
  - "8"

script:
  - yarn run test

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g now

before_deploy:
  - yarn run build
  - rm build/static/js/main.*.js.map

deploy:
  provider: script
  script: now alias `now build -t=$NOW_TOKEN --public` $URL_PROD -t=$NOW_TOKEN
  on:
    branch: master
  skip_cleanup: true